name: My workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
# oh my god, the number of spaces before - is important (must be 4)
#    - run: bundle exec rake #from the ruby-setup code. do not use
# this updated webpacker
    - run: yarn install --check-files
# now I can run the test
    - run: bin/rails test
