name: My workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2 # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
#    - run: bundle install # bundle exec rake
#    - run: yarn install --check-files
#    - run: bin/rake db:migrate
     - run: bin/rails test

